import json, sys

content = [
  {"type": "h1", "text": "执行摘要"},
  {"type": "body", "text": "2026年2月28日美以对伊开战以来，黄金市场经历了三轮冲击波。本报告在汇总11家投行目标价的基础上，首次纳入3月30日鲍威尔哈佛讲话的最新市场反应，以及"2026年降息归零"这一重磅转变。"},
  {"type": "image", "path": "/tmp/gold-charts-final.png", "caption": "图1：黄金历史走势与各投行目标价对比"},
  {"type": "image", "path": "/tmp/gold-timeline-final.png", "caption": "图2：黄金走势时间线（1月-3月）-- 战争 + 美联储 + 鲍威尔讲话全记录"},
  {"type": "spacer", "pt": 8},
  {"type": "h1", "text": "二、2026下半年各大投行目标价汇总（当前 $4,472）"},
  {"type": "table", "headers": ["机构", "目标价", "涨幅", "时间", "来源"],
    "rows": [
      ["摩根大通", "$6,300", "+41%", "2026年底", "JPMorgan, Feb 2026 (Reuters)"],
      ["瑞银", "$6,200", "+39%", "2026年3/6/9月", "UBS Precious Metals, Feb 2026"],
      ["高盛", "$5,400", "+21%", "2026年底", "Goldman Sachs, Jan 22 2026 (Reuters)"],
      ["德意志银行", "$6,000", "+35%", "2026年底", "Deutsche Bank, Jan 2026"],
      ["富国银行", "$6,100-$6,300", "+37-41%", "2026年底", "Wells Fargo, Feb 2026"],
      ["BMO", "$6,350", "+43%", "2026年Q4", "BMO Commodity, Jan 2026"],
      ["道明证券", "$5,800", "+30%", "2026下半年", "TD Securities, Feb 2026"],
      ["花旗", "$7,200-$7,500", "+62-68%", "2026年内", "Citi Private Bank, Jan 2026"],
      ["Jefferies", "$6,600", "+48%", "2026年底", "Jefferies, Feb 2026"],
      ["Yardeni", "$6,000", "+35%", "2026年底", "Yardeni Research, Jan 2026"],
      ["CIBC", "$5,500", "+23%", "2026年底", "CIBC Commodity, Jan 2026"]
    ]},
  {"type": "h1", "text": "三、3月30日鲍威尔哈佛讲话：最重磅的降息预期清零"},
  {"type": "h2", "text": "3.1 鲍威尔说了什么"},
  {"type": "body", "text": "3月30日，美联储主席杰罗姆·鲍威尔在哈佛大学发表讲话，释放了本届美联储有史以来最强烈的鹰派信号："},
  {"type": "body", "text": "明确警告：伊朗战争正在给经济引入"新通胀"（new inflation），这一定性直接将能源价格冲击定性为结构性而非临时性因素。"},
  {"type": "body", "text": "美联储官员正在重新考虑是否还要在2026年降息----此前市场普遍预期降息1次，而目前市场定价已完全转向：2026年全年降息概率归零，即零次降息。"},
  {"type": "callout", "text": "原文：Powell said Monday "it is important to closely monitor inflation amid a spike in energy prices from the Iran war." \n来源：Reporter Herald / PBS NewsHour, Mar 30 2026 | realtor.com 'Fed May Not Cut Rates at All in 2026'"},
  {"type": "h2", "text": "3.2 市场即时反应"},
  {"type": "body", "text": "股债双杀：股市和债市同步下跌，10年期国债收益率上升（债券价格下跌）。"},
  {"type": "body", "text": "美元走强：美元指数进一步攀升，美元成为资金避风港，黄金承压。"},
  {"type": "body", "text": "黄金走势：讲话后黄金短线跳水，跌破$4,500，但随后逢低买盘支撑，今日（3月31日）小幅反弹至$4,472（+0.12%）。"},
  {"type": "body", "text": "实际收益率攀升：若能源价格持续高企，名义利率不变意味着实际利率上升，对零息资产黄金构成直接压力。"},
  {"type": "callout", "text": "Morningstar评论："Wall Street has been slow to hear what Powell has said -- at least since the Fed chair belatedly realized that inflation had turned intractable in 2022." 若债市持续因通胀担忧抛售，将推动债券利率上升，这通常对黄金构成双重压力。来源：Morningstar, Mar 18 2026"},
  {"type": "h2", "text": "3.3 从"1次降息"到"零降息"的意义"},
  {"type": "body", "text": "就在一个月前，市场还定价2026年降息3-4次。这一预期是黄金能从$2,000涨至$5,000的核心逻辑之一。如今降息预期彻底消失，支撑黄金的货币政策红利已被完全定价出。"},
  {"type": "body", "text": "当前黄金的支撑逻辑已从"货币宽松预期"切换至"地缘风险+去美元化"----而前者才是过去几年最核心的推动力。"},
  {"type": "h1", "text": "四、美伊战争对黄金的实质性影响分析"},
  {"type": "h2", "text": "4.1 战争悖论：开打后金价不升反跌"},
  {"type": "body", "text": "2月28日美以对伊发动军事打击后，市场走出了教科书上从未见过的战争悖论：战争开打，黄金反而从$5,423跌至$4,472，跌幅超17%。"},
  {"type": "body", "text": "传导路径：战争 -> 油价暴涨 -> 通胀压力加剧 -> 美联储被迫偏鹰 -> 美元走强 -> 黄金承压。这与俄乌战争初期（2022年）走势如出一辙。"},
  {"type": "h2", "text": "4.2 霍尔木兹海峡：4月中旬是核心节点"},
  {"type": "body", "text": "全球约20%的石油运输经过霍尔木兹海峡。当前海峡封闭（流量仅正常水平的5%），油价$110+。能源高管警告：若4月中旬前仍未重开，将出现更严重的供应中断，油价可能升至$135-$157。"},
  {"type": "h2", "text": "4.3 战争三种情景（更新）"},
  {"type": "body", "text": "情景A（35%）：战争持续但不升级，油价$100-130高位震荡。美联储被迫全年按兵不动，金价$4,000-4,800区间整固。"},
  {"type": "body", "text": "情景B（25%）：战争快速缓和，霍尔木兹重开，油价回落。通胀压力骤降，美联储降息预期重启，美元走弱，黄金迎来新一轮上涨，突破$5,500。"},
  {"type": "body", "text": "情景C（40%）：冲突扩大化（核设施打击），霍尔木兹持续封闭数月，油价突破$150。滞胀全面爆发，美联储可能被迫加息----美元走强压制黄金，但恶性通胀同时支撑黄金，两股力量激烈博弈。"},
  {"type": "h1", "text": "五、关键价位与操作建议"},
  {"type": "table", "headers": ["类型", "价格", "说明"],
    "rows": [
      ["当前价格", "$4,472", "2026年3月31日（鲍威尔讲话后小幅反弹）"],
      ["即时支撑", "$4,654", "Murrey Math 4/8线，多指标共振"],
      ["近期低点", "$4,402", "3月中旬触底反弹位"],
      ["关键支撑", "$4,000-$4,200", "整数大关+EMA200区间"],
      ["分水岭", "$4,800", "若重返$4,800上方，多头情绪恢复"],
      ["前高区间", "$5,184-$5,423", "2026年1-3月高点"],
      ["投行共识", "$6,000-$6,300", "年末目标"]
    ]},
  {"type": "body", "text": "机构投资者：配置10-15%，$4,200以下视为战略买入机会；当前以观望为主，等待鲍威尔下一步信号。"},
  {"type": "body", "text": "个人投资者：$4,300以下分批买入黄金ETF，止损$3,900，目标$5,500-$6,000。"},
  {"type": "body", "text": "杠杆投资者：$4,400以下可轻仓做多，止损$3,900；重点关注4月中旬霍尔木兹消息----任何缓和信号都可能触发快速反弹。"},
  {"type": "h1", "text": "六、风险提示（更新）"},
  {"type": "callout", "text": "美联储零降息：2026年全年不降息情景已初步确认，实际利率上升对黄金构成系统性压力"},
  {"type": "callout", "text": "鲍威尔鹰派持续：若CPI持续高企，美联储官员将持续释放鹰派信号，限制黄金上涨空间"},
  {"type": "callout", "text": "战争缓和：外交停火导致油价回落，黄金失去地缘溢价，但降息预期重启或提供新支撑"},
  {"type": "callout", "text": "滞胀陷阱（最危险情景）：油价持续$150+且美联储被迫加息，实际利率走向极不确定"},
  {"type": "h1", "text": "七、数据来源"},
  {"type": "numbered", "text": "Reporter Herald / PBS NewsHour, Mar 30 2026 - 'Powell says Fed monitoring energy price spikes, options limited' (reporterherald.com)"},
  {"type": "numbered", "text": "Realtor.com, Mar 30 2026 - 'Fed May Not Cut Rates at All in 2026 as Powell Says Inflation Impact of Iran War Remains Unclear' (realtor.com)"},
  {"type": "numbered", "text": "Morningstar, Mar 18 2026 - 'Powell warns of new inflation from the Iran conflict as gas prices jump 30%' (morningstar.com)"},
  {"type": "numbered", "text": "TheStreet, Mar 2026 - 'Analysts have a message for gold investors before the Fed meeting' (thestreet.com)"},
  {"type": "numbered", "text": "Sunday Guardian Live, Mar 31 2026 - 'Gold edges higher to $4,472 on month-end' (sundayguardianlive.com)"},
  {"type": "numbered", "text": "LiteFinance, Mar 31 2026 - 'Gold expected to trade between $4,376-$4,577' (litefinance.org)"},
  {"type": "numbered", "text": "Chronicle Journal, Mar 27 2026 - 'Crude Oil Tops $110 as Strait of Hormuz Closure' (chroniclejournal.com)"},
  {"type": "numbered", "text": "Reuters, Feb 25 2026 - 'JP Morgan expects gold $6,300/oz by end-2026' (reuters.com)"},
  {"type": "numbered", "text": "Reuters, Jan 22 2026 - 'Goldman Sachs raises 2026 gold forecast to $5,400/oz' (reuters.com)"},
  {"type": "body", "text": "本报告仅供参考，不构成投资建议。"}
]

workdir = sys.argv[1]
with open(workdir + '/content.json', 'w', encoding='utf-8') as f:
    json.dump(content, f, ensure_ascii=False, indent=2)
print("OK")
