#!/bin/bash

# Skill Auto-Iteration 测试脚本

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 Skill Auto-Iteration 系统测试"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. 检查 Claude Code
echo "✅ 1. 检查 Claude Code："
which claude && claude --version | head -1

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 2. 检查 OpenClaw Skills："
openclaw skills list | grep -E "coding-agent|skill-auto" || echo "Skills 已加载"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 3. 测试 Claude Code 集成："

# 创建测试目录
TEST_DIR=~/Projects/skill-test-$(date +%s)
mkdir -p $TEST_DIR
cd $TEST_DIR
git init

echo "📁 测试目录：$TEST_DIR"

# 运行 Claude Code 任务（使用 coding-agent Skill）
echo ""
echo "🚀 运行 Claude Code 任务："

# 临时创建一个 OpenClaw 消息脚本来测试
cat << 'MESSAGE_EOF' > ~/openclaw_test_msg.sh
#!/bin/bash
# 这个脚本模拟发送消息给 OpenClaw

# 实际使用中，应该通过 Telegram/其他渠道发送
# 这里我们直接演示流程

echo "📝 演示 Skill Auto-Iteration 流程："
echo ""
echo "场景：Claude Code 执行开发任务时遇到错误"
echo ""
echo "1. 错误发生：command not found: xxx"
echo "2. 捕获错误：记录到 ~/openclaw_error_log.txt"
echo "3. 分析原因：缺少依赖/配置问题"
echo "4. 生成修复：添加依赖检查/更新文档"
echo "5. 更新 Skill：在 SKILL.md 中添加错误处理"
echo "6. 推送到 GitHub：git commit & push"
echo ""
echo "✅ 错误已学习！Skill 已改进！"
MESSAGE_EOF

chmod +x ~/openclaw_test_msg.sh
bash ~/openclaw_test_msg.sh

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 4. 创建自动学习触发器："

# 创建学习日志文件
ERROR_LOG=~/.openclaw/workspace/skill_errors.log
touch $ERROR_LOG
echo "📝 错误日志：$ERROR_LOG"

# 创建学习总结
SUMMARY_FILE=~/.openclaw/workspace/skill_learning_summary.md
cat << 'SUMMARY_EOF' > $SUMMARY_FILE
# Skill Learning Summary

## 自动学习记录

### 日期：$(date +%Y-%m-%d)

#### 学习的错误：

1. **错误类型**：[待记录]
   - 原因：
   - 解决方案：
   - 预防措施：

#### 改进的 Skills：
- skill-auto-iteration：创建了自动学习框架
- coding-agent：集成了 Claude Code 操控

#### 待改进：
- [ ] 配置定时错误检查
- [ ] 添加自动修复规则
- [ ] 集成 GitHub Actions

#### 下次迭代：
- [ ] 完善错误分析
- [ ] 添加更多测试用例
- [ ] 优化学习流程

---

*Generated by Skill Auto-Iteration System*
SUMMARY_EOF

echo "📊 学习总结：$SUMMARY_FILE"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Skill Auto-Iteration 系统已就绪！"
echo ""
echo "📚 文档位置："
echo "   - Skill：~/.openclaw/workspace/skills/skill-auto-iteration/SKILL.md"
echo "   - 错误日志：$ERROR_LOG"
echo "   - 学习总结：$SUMMARY_FILE"
echo ""
echo "🚀 接下来："
echo "   1. 在 OpenClaw 中使用这个 Skill"
echo "   2. 执行开发任务（Claude Code）"
echo "   3. 遇到错误时自动学习"
echo "   4. 查看学习总结"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 清理测试目录
echo ""
echo "🧹 清理测试文件..."
rm -rf $TEST_DIR
rm ~/openclaw_test_msg.sh

echo "✅ 测试完成！"

